### ISSUE TITLE
Error when compiling with gcc 10.1.0

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/metaverse#399]
I get the following error when i try to compile with gcc 10.1.0:

In file included from /home/cangr/projects/metaverse/include/metaverse/bitcoin/chain/header.hpp:41,
                 from /home/cangr/projects/metaverse/include/metaverse/bitcoin/chain/block.hpp:29,
                 from /home/cangr/projects/metaverse/include/metaverse/bitcoin/message/block_message.hpp:28,
                 from /home/cangr/projects/metaverse/include/metaverse/bitcoin/messages.hpp:26,
                 from /home/cangr/projects/metaverse/include/metaverse/bitcoin.hpp:23,
                 from /home/cangr/projects/metaverse/src/lib/bitcoin/chain/attachment/account/account.cpp:34:
/home/cangr/projects/metaverse/include/metaverse/consensus/libdevcore/SHA3.h: In function ‘libbitcoin::SecureFixedHash<32> libbitcoin::sha3Secure(libbitcoin::bytesConstRef)’:
/home/cangr/projects/metaverse/include/metaverse/consensus/libdevcore/SHA3.h:41:131: error: implicitly-declared ‘constexpr libbitcoin::SecureFixedHash<32>::SecureFixedHash(const libbitcoin::SecureFixedHash<32>&)’ is deprecated [-Werror=deprecated-copy]
   41 | inline SecureFixedHash<32> sha3Secure(bytesConstRef _input) { SecureFixedHash<32> ret; sha3(_input, ret.writable().ref()); return ret; }
      |                                                                                                                                   ^~~
In file included from /home/cangr/projects/metaverse/include/metaverse/bitcoin/chain/header.hpp:38,
                 from /home/cangr/projects/metaverse/include/metaverse/bitcoin/chain/block.hpp:29,
                 from /home/cangr/projects/metaverse/include/metaverse/bitcoin/message/block_message.hpp:28,
                 from /home/cangr/projects/metaverse/include/metaverse/bitcoin/messages.hpp:26,
                 from /home/cangr/projects/metaverse/include/metaverse/bitcoin.hpp:23,
                 from /home/cangr/projects/metaverse/src/lib/bitcoin/chain/attachment/account/account.cpp:34:
/home/cangr/projects/metaverse/include/metaverse/consensus/libdevcore/FixedHash.h:239:25: note: because ‘libbitcoin::SecureFixedHash<32>’ has user-provided ‘libbitcoin::SecureFixedHash<T>& libbitcoin::SecureFixedHash<T>::operator=(const libbitcoin::SecureFixedHash<T>&) [with unsigned int T = 32]’
  239 |     SecureFixedHash<T>& operator=(SecureFixedHash<T> const& _c)
      |                         ^~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/lib/bitcoin/CMakeFiles/bitcoin_static.dir/build.make:86: src/lib/bitcoin/CMakeFiles/bitcoin_static.dir/chain/attachment/account/account.cpp.o] Error 1
make[2]: Leaving directory '/home/cangr/projects/metaverse/build'
make[1]: *** [CMakeFiles/Makefile2:694: src/lib/bitcoin/CMakeFiles/bitcoin_static.dir/all] Error 2
make[1]: Leaving directory '/home/cangr/projects/metaverse/build'
make: *** [Makefile:164: all] Error 2

**Comment by canguruhh** [comment]
Created a dockerfile that contains the toolchain. I will create a PR soon
