### ISSUE TITLE
Make Fails

### ISSUE THREAD

**Issue by RyanF109** [mvs-org/metaverse#170]
Make is failing. I built and installed all dependencies and getting this...

[ 75%] Building CXX object src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/wallet/issuemore.cpp.o
cd /home/miner/metaverse/build/src/lib/explorer && /usr/bin/c++   -DBCX_STATIC=1 -I/home/miner/metaverse/contrib -I/home/miner/metaverse/include -I/usr/local/include  -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG   -o CMakeFiles/explorer_static.dir/extensions/wallet/issuemore.cpp.o -c /home/miner/metaverse/src/lib/explorer/extensions/wallet/issuemore.cpp
[ 75%] Building CXX object src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/wallet/exportaccountasfile.cpp.o
cd /home/miner/metaverse/build/src/lib/explorer && /usr/bin/c++   -DBCX_STATIC=1 -I/home/miner/metaverse/contrib -I/home/miner/metaverse/include -I/usr/local/include  -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG   -o CMakeFiles/explorer_static.dir/extensions/wallet/exportaccountasfile.cpp.o -c /home/miner/metaverse/src/lib/explorer/extensions/wallet/exportaccountasfile.cpp
[ 75%] Building CXX object src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/wallet/issuemorefrom.cpp.o
cd /home/miner/metaverse/build/src/lib/explorer && /usr/bin/c++   -DBCX_STATIC=1 -I/home/miner/metaverse/contrib -I/home/miner/metaverse/include -I/usr/local/include  -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG   -o CMakeFiles/explorer_static.dir/extensions/wallet/issuemorefrom.cpp.o -c /home/miner/metaverse/src/lib/explorer/extensions/wallet/issuemorefrom.cpp
[ 76%] Building CXX object src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/wallet/createmultisig.cpp.o
cd /home/miner/metaverse/build/src/lib/explorer && /usr/bin/c++   -DBCX_STATIC=1 -I/home/miner/metaverse/contrib -I/home/miner/metaverse/include -I/usr/local/include  -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG   -o CMakeFiles/explorer_static.dir/extensions/wallet/createmultisig.cpp.o -c /home/miner/metaverse/src/lib/explorer/extensions/wallet/createmultisig.cpp
[ 76%] Building CXX object src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/wallet/listassets.cpp.o
cd /home/miner/metaverse/build/src/lib/explorer && /usr/bin/c++   -DBCX_STATIC=1 -I/home/miner/metaverse/contrib -I/home/miner/metaverse/include -I/usr/local/include  -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG   -o CMakeFiles/explorer_static.dir/extensions/wallet/listassets.cpp.o -c /home/miner/metaverse/src/lib/explorer/extensions/wallet/listassets.cpp
[ 76%] Building CXX object src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/wallet/deleteaccount.cpp.o
cd /home/miner/metaverse/build/src/lib/explorer && /usr/bin/c++   -DBCX_STATIC=1 -I/home/miner/metaverse/contrib -I/home/miner/metaverse/include -I/usr/local/include  -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG   -o CMakeFiles/explorer_static.dir/extensions/wallet/deleteaccount.cpp.o -c /home/miner/metaverse/src/lib/explorer/extensions/wallet/deleteaccount.cpp
[ 76%] Building CXX object src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/wallet/addmultisigaddress.cpp.o
cd /home/miner/metaverse/build/src/lib/explorer && /usr/bin/c++   -DBCX_STATIC=1 -I/home/miner/metaverse/contrib -I/home/miner/metaverse/include -I/usr/local/include  -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG   -o CMakeFiles/explorer_static.dir/extensions/wallet/addmultisigaddress.cpp.o -c /home/miner/metaverse/src/lib/explorer/extensions/wallet/addmultisigaddress.cpp
[ 76%] Building CXX object src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/wallet/xfetchbalance.cpp.o
cd /home/miner/metaverse/build/src/lib/explorer && /usr/bin/c++   -DBCX_STATIC=1 -I/home/miner/metaverse/contrib -I/home/miner/metaverse/include -I/usr/local/include  -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG   -o CMakeFiles/explorer_static.dir/extensions/wallet/xfetchbalance.cpp.o -c /home/miner/metaverse/src/lib/explorer/extensions/wallet/xfetchbalance.cpp
[ 77%] Building CXX object src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/account_query_helper.cpp.o
cd /home/miner/metaverse/build/src/lib/explorer && /usr/bin/c++   -DBCX_STATIC=1 -I/home/miner/metaverse/contrib -I/home/miner/metaverse/include -I/usr/local/include  -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG   -o CMakeFiles/explorer_static.dir/extensions/account_query_helper.cpp.o -c /home/miner/metaverse/src/lib/explorer/extensions/account_query_helper.cpp
[ 77%] Building CXX object src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/command_assistant.cpp.o
cd /home/miner/metaverse/build/src/lib/explorer && /usr/bin/c++   -DBCX_STATIC=1 -I/home/miner/metaverse/contrib -I/home/miner/metaverse/include -I/usr/local/include  -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG   -o CMakeFiles/explorer_static.dir/extensions/command_assistant.cpp.o -c /home/miner/metaverse/src/lib/explorer/extensions/command_assistant.cpp
In file included from /usr/include/boost/property_tree/json_parser/detail/read.hpp:13:0,
                 from /usr/include/boost/property_tree/json_parser.hpp:16,
                 from /home/miner/metaverse/src/lib/explorer/extensions/command_assistant.cpp:29:
/usr/include/boost/property_tree/json_parser/detail/parser.hpp: In member function ‘void boost::property_tree::json_parser::detail::string_callback_adapter<Callbacks, Encoding, Iterator, std::input_iterator_tag>::process_codepoint(Sentinel, EncodingErrorFn)’:
/usr/include/boost/property_tree/json_parser/detail/parser.hpp:217:52: error: ‘_1’ was not declared in this scope
                             boost::ref(callbacks), _1),
                                                    ^
/usr/include/boost/property_tree/json_parser/detail/parser.hpp:217:52: note: suggested alternatives:
In file included from /usr/include/c++/5/memory:79:0,
                 from /home/miner/metaverse/include/metaverse/bitcoin/utility/monitor.hpp:26,
                 from /home/miner/metaverse/include/metaverse/bitcoin/utility/assert.hpp:39,
                 from /home/miner/metaverse/include/metaverse/bitcoin/impl/utility/data.ipp:27,
                 from /home/miner/metaverse/include/metaverse/bitcoin/utility/data.hpp:156,
                 from /home/miner/metaverse/include/metaverse/bitcoin/message/network_address.hpp:28,
                 from /home/miner/metaverse/include/metaverse/bitcoin/constants.hpp:28,
                 from /home/miner/metaverse/include/metaverse/bitcoin.hpp:19,
                 from /home/miner/metaverse/include/metaverse/explorer/dispatch.hpp:25,
                 from /home/miner/metaverse/src/lib/explorer/extensions/command_assistant.cpp:21:
/usr/include/c++/5/functional:782:34: note:   ‘std::placeholders::_1’
     extern const _Placeholder<1> _1;
                                  ^
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37:0,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/mpl/apply.hpp:24,
                 from /usr/include/boost/mpl/aux_/iter_apply.hpp:17,
                 from /usr/include/boost/mpl/aux_/find_if_pred.hpp:14,
                 from /usr/include/boost/mpl/find_if.hpp:17,
                 from /usr/include/boost/multiprecision/number.hpp:13,
                 from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /home/miner/metaverse/include/metaverse/bitcoin/chain/header.hpp:24,
                 from /home/miner/metaverse/include/metaverse/bitcoin/chain/block.hpp:29,
                 from /home/miner/metaverse/include/metaverse/bitcoin/message/block_message.hpp:28,
                 from /home/miner/metaverse/include/metaverse/bitcoin/messages.hpp:28,
                 from /home/miner/metaverse/include/metaverse/bitcoin.hpp:23,
                 from /home/miner/metaverse/include/metaverse/explorer/dispatch.hpp:25,
                 from /home/miner/metaverse/src/lib/explorer/extensions/command_assistant.cpp:21:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
 typedef arg<1> _1;
                ^
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
In file included from /usr/include/boost/property_tree/json_parser/detail/read.hpp:13:0,
                 from /usr/include/boost/property_tree/json_parser.hpp:16,
                 from /home/miner/metaverse/src/lib/explorer/extensions/command_assistant.cpp:29:
/usr/include/boost/property_tree/json_parser/detail/parser.hpp: In member function ‘void boost::property_tree::json_parser::detail::parser<Callbacks, Encoding, Iterator, Sentinel>::feed(unsigned int)’:
/usr/include/boost/property_tree/json_parser/detail/parser.hpp:520:72: error: ‘_1’ was not declared in this scope
                                                 boost::ref(callbacks), _1));
                                                                        ^
/usr/include/boost/property_tree/json_parser/detail/parser.hpp:520:72: note: suggested alternatives:
In file included from /usr/include/c++/5/memory:79:0,
                 from /home/miner/metaverse/include/metaverse/bitcoin/utility/monitor.hpp:26,
                 from /home/miner/metaverse/include/metaverse/bitcoin/utility/assert.hpp:39,
                 from /home/miner/metaverse/include/metaverse/bitcoin/impl/utility/data.ipp:27,
                 from /home/miner/metaverse/include/metaverse/bitcoin/utility/data.hpp:156,
                 from /home/miner/metaverse/include/metaverse/bitcoin/message/network_address.hpp:28,
                 from /home/miner/metaverse/include/metaverse/bitcoin/constants.hpp:28,
                 from /home/miner/metaverse/include/metaverse/bitcoin.hpp:19,
                 from /home/miner/metaverse/include/metaverse/explorer/dispatch.hpp:25,
                 from /home/miner/metaverse/src/lib/explorer/extensions/command_assistant.cpp:21:
/usr/include/c++/5/functional:782:34: note:   ‘std::placeholders::_1’
     extern const _Placeholder<1> _1;
                                  ^
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37:0,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/mpl/apply.hpp:24,
                 from /usr/include/boost/mpl/aux_/iter_apply.hpp:17,
                 from /usr/include/boost/mpl/aux_/find_if_pred.hpp:14,
                 from /usr/include/boost/mpl/find_if.hpp:17,
                 from /usr/include/boost/multiprecision/number.hpp:13,
                 from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /home/miner/metaverse/include/metaverse/bitcoin/chain/header.hpp:24,
                 from /home/miner/metaverse/include/metaverse/bitcoin/chain/block.hpp:29,
                 from /home/miner/metaverse/include/metaverse/bitcoin/message/block_message.hpp:28,
                 from /home/miner/metaverse/include/metaverse/bitcoin/messages.hpp:28,
                 from /home/miner/metaverse/include/metaverse/bitcoin.hpp:23,
                 from /home/miner/metaverse/include/metaverse/explorer/dispatch.hpp:25,
                 from /home/miner/metaverse/src/lib/explorer/extensions/command_assistant.cpp:21:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
 typedef arg<1> _1;
                ^
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
src/lib/explorer/CMakeFiles/explorer_static.dir/build.make:1841: recipe for target 'src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/command_assistant.cpp.o' failed
make[2]: *** [src/lib/explorer/CMakeFiles/explorer_static.dir/extensions/command_assistant.cpp.o] Error 1
make[2]: Leaving directory '/home/miner/metaverse/build'
CMakeFiles/Makefile2:819: recipe for target 'src/lib/explorer/CMakeFiles/explorer_static.dir/all' failed
make[1]: *** [src/lib/explorer/CMakeFiles/explorer_static.dir/all] Error 2
make[1]: Leaving directory '/home/miner/metaverse/build'
Makefile:141: recipe for target 'all' failed
make: *** [all] Error 2

Any help would be much appreciated.

**Comment by wdyoschina** [comment]
Hi RyanF109,
sorry for late response !
your compile error is caused by boost lib version issue.  you can find resolution in metaverse README "Library Dependencies" partition.  I paste those words below.

If build with boost 1.59~1.63, get compiling error on json_parser 'placeholders::_1' caused by boost bug:

/usr/local/include/boost/property_tree/json_parser/detail/parser.hpp:217:52: error: ‘_1’ was not declared in this scope
Please upgrade to 1.64, or modify parser.hpp manually at first. See boost issue details: https://github.com/boostorg/property_tree/pull/26

**Comment by wdyoschina** [comment]
in my opinion, my suggestion can resolve the issue. so i close it ! open it if any new problem ! Thanks
