### ISSUE TITLE
oldder than MVS version v0.7.3 => parser.hpp:217:52: error: ‘_1’ was not declared in this scope

### ISSUE THREAD

**Issue by betachen** [mvs-org/metaverse#216]
under MVS v0.7.3 version source code has issue:
-----------------

compiling error on json_parser 'placeholders::_1' caused by boost issue:`/usr/local/include/boost/property_tree/json_parser/detail/parser.hpp:217:52: error: ‘_1’ was not declared in this scope`.

If build with boost 1.59~1.63, will get compiling error on json_parser 'placeholders::_1' caused by boost bug:
>/usr/local/include/boost/property_tree/json_parser/detail/parser.hpp:217:52: error: ‘_1’ was not declared in this scope.
                                                                                
Please upgrade to 1.64, or modify `parser.hpp` manually at first. Using:        
```                                                                             
sed -i -e '/#include <boost\/bind.hpp>/a #include <boost\/bind\/placeholders.hpp>' -e 's/boost::ref(callbacks), _1)/boost::ref(callbacks), boost::placeholders::_1)/g' parser.hpp
```                                                                             
See boost [bug issue details](https://github.com/boostorg/property_tree/pull/26).

**Comment by betachen** [comment]
#189 
replace completed ,then close.
